"""empty message

Revision ID: b046abae7dff
Revises: 4aac5bc4af20
Create Date: 2015-12-28 15:50:48.441543

"""

# revision identifiers, used by Alembic.
revision = 'b046abae7dff'
down_revision = '4aac5bc4af20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
